server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?user=postgres.rzddhksaimpzmdroixbk&password=Bugwarts-IT-23
    username: postgres.rzddhksaimpzmdroixbk
    password: Bugwarts-IT-23

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true